[tool.poetry]
name = "cif"
version = "0.1.0"
description = ""
authors = ["Jiri Raja <raja@ics.muni.cz>"]
readme = "README.md"
include = ["images"]

[tool.poetry.dependencies]
python = "^3.11"
docker = "^7.1.0"

[tool.poetry.group.dev.dependencies]
black = "^24.8.0"

[tool.poetry.scripts]
cif = 'cif.main:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
